openapi: 3.0.3
info:
  title: dAIsy Tools - Amadeus and IATA
  version: 1.1.1
  description: HTTP tools for the Bedrock Agent to search flights via Amadeus and resolve IATA codes.
servers:
  - url: https://origin-daisy.onrender.com
paths:
  /tools/amadeus/search:
    description: Amadeus Flight Offers Search adapter exposed by the proxy server.
    post:
      operationId: amadeusSearch
      summary: Search flight offers
      description: Submit a request to Amadeus Flight Offers Search via the proxy and retrieve LH-only offers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - originLocationCode
                - destinationLocationCode
                - departureDate
                - adults
              properties:
                originLocationCode:
                  type: string
                  description: IATA origin code (for example, MUC)
                destinationLocationCode:
                  type: string
                  description: IATA destination code (for example, ZRH)
                departureDate:
                  type: string
                  format: date
                  description: Outbound date in ISO 8601 format (YYYY-MM-DD)
                returnDate:
                  type: string
                  format: date
                  nullable: true
                  description: Optional return date in ISO 8601 format (YYYY-MM-DD)
                adults:
                  type: integer
                  minimum: 1
                  default: 1
                  description: Number of adult passengers
                children:
                  type: integer
                  minimum: 0
                  description: Number of child passengers
                infants:
                  type: integer
                  minimum: 0
                  description: Number of infant passengers
                nonStop:
                  type: boolean
                  default: false
                  description: If true, return only non-stop options
                travelClass:
                  type: string
                  enum:
                    - ECONOMY
                    - PREMIUM_ECONOMY
                    - BUSINESS
                    - FIRST
                  description: Preferred cabin class
                currencyCode:
                  type: string
                  description: Currency code (ISO 4217), for example EUR
                includedAirlineCodes:
                  type: string
                  description: Only consider these airline codes (comma-separated)
                excludedAirlineCodes:
                  type: string
                  description: Exclude these airline codes (comma-separated)
                max:
                  type: integer
                  minimum: 1
                  maximum: 250
                  default: 10
                  description: Maximum number of offers to return
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  offers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Offer"
                  raw:
                    type: object
        "400":
          description: Bad Request
        "502":
          description: Upstream error

  /tools/iata/lookup:
    description: Deterministic IATA resolver backed by the proxy server.
    get:
      operationId: iataLookup
      summary: Resolve IATA code or city or airport name
      description: Look up IATA codes or names deterministically using the proxy database.
      parameters:
        - in: query
          name: term
          required: true
          schema:
            type: string
          description: IATA code (for example, MUC) or partial city or airport name (for example, Munich)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object

  /tools/amadeus/flex:
    description: One-call flexible dates selection and LH-only pricing (one-way).
    get:
      operationId: amadeusFlex
      summary: Flexible dates priced list
      description: Request the proxy to select cheapest days and return LH-only priced offers for one-way searches.
      parameters:
        - in: query
          name: origin
          required: true
          schema:
            type: string
          description: IATA origin code (for example, MUC)
        - in: query
          name: destination
          required: true
          schema:
            type: string
          description: IATA destination code (for example, ZRH)
        - in: query
          name: departureDate
          required: false
          schema:
            type: string
          description: Specific departure date or inclusive range (YYYY-MM-DD or YYYY-MM-DD,YYYY-MM-DD)
        - in: query
          name: month
          required: false
          schema:
            type: string
          description: Month window (YYYY-MM); alternative to departureDate
        - in: query
          name: oneWay
          required: false
          schema:
            type: boolean
            default: true
          description: Must be true to return priced results (calendar is internal)
        - in: query
          name: nonStop
          required: false
          schema:
            type: boolean
            default: false
          description: If true, return only non-stop options
        - in: query
          name: maxPrice
          required: false
          schema:
            type: integer
          description: Maximum price per traveler (positive integer)
        - in: query
          name: viewBy
          required: false
          schema:
            type: string
            enum:
              - DATE
              - DURATION
              - WEEK
          description: Optional calendar grouping (defaults to DATE for one-way)
        - in: query
          name: currencyCode
          required: false
          schema:
            type: string
          description: Currency code (ISO 4217), for example EUR
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 10
            default: 5
          description: Maximum number of cheapest days to select from calendar
        - in: query
          name: priceLimit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 10
          description: Maximum number of days to price (defaults to limit)
        - in: query
          name: adults
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Number of adult passengers
        - in: query
          name: travelClass
          required: false
          schema:
            type: string
            enum:
              - ECONOMY
              - PREMIUM_ECONOMY
              - BUSINESS
              - FIRST
          description: Preferred cabin class
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: object
                  priced:
                    type: array
                    items:
                      type: object
                      properties:
                        departureDate:
                          type: string
                          format: date
                        offers:
                          type: array
                          items:
                            $ref: "#/components/schemas/Offer"
                required:
                  - priced
        "400":
          description: Bad Request
        "502":
          description: Upstream error

  /tools/s3escalator:
    description: Upload artifacts (logs, transcripts, alerts) through the proxy escalator service.
    post:
      operationId: uploadEscalator
      summary: Upload a debug or transcript artifact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EscalatorUploadRequest"
      responses:
        "200":
          description: Upload completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EscalatorUploadResponse"
        "400":
          description: Missing required fields or file payload.
        "502":
          description: Escalator service error.

  /tools/antiPhaser:
    description: Dedicated microservice for parsing natural-language date phrases using chrono-node/luxon.
    get:
      operationId: antiPhaserGet
      summary: Interpret a date phrase (GET)
      parameters:
        - in: query
          name: phrase
          required: true
          schema:
            type: string
          description: Phrase to interpret, e.g. `next Friday at 2pm`.
        - in: query
          name: timezone
          required: false
          schema:
            type: string
          description: IANA timezone (default UTC).
        - in: query
          name: referenceDate
          required: false
          schema:
            type: string
          description: ISO date to anchor relative phrases (defaults to current day).
      responses:
        "200":
          description: Parsed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AntiPhaserResponse"
        "400":
          description: Invalid or missing phrase.
        "502":
          description: antiPhaser service error.
    post:
      operationId: antiPhaserPost
      summary: Interpret a date phrase (POST)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AntiPhaserRequest"
      responses:
        "200":
          description: Parsed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AntiPhaserResponse"
        "400":
          description: Invalid or missing phrase.
        "502":
          description: antiPhaser service error.

  /tools/derDrucker/wannaCandy:
    description: Format LH-Group itinerary offers into Markdown via the derDrucker service.
    post:
      operationId: derDruckerWannaCandy
      summary: Format offers into Markdown
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DerDruckerMarkdownRequest"
      responses:
        "200":
          description: Markdown generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DerDruckerMarkdownResponse"
        "400":
          description: Input payload invalid.
        "502":
          description: derDrucker service error.

  /tools/derDrucker/generateTickets:
    description: Produce base64-encoded PDF boarding passes via derDrucker.
    post:
      operationId: derDruckerGenerateTickets
      summary: Generate PDF tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DerDruckerTicketRequest"
      responses:
        "200":
          description: PDF tickets generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DerDruckerTicketResponse"
        "400":
          description: Input payload invalid.
        "502":
          description: derDrucker service error.

  /tools/give_me_tools:
    description: Inspect the proxy's tool catalog at runtime.
    get:
      operationId: giveMeTools
      summary: Enumerate available proxy tools
      responses:
        "200":
          description: Tool catalog retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToolCatalogResponse"
        "502":
          description: Proxy error when fetching tool list.

  /tools/datetime/interpret:
    description: In-proxy interpretation fallback that mirrors TimePhraseParser.
    post:
      operationId: proxyDatetimeInterpret
      summary: Interpret a natural-language date/time phrase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DatetimeInterpretRequest"
      responses:
        "200":
          description: Phrase interpreted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatetimeInterpretResponse"
        "400":
          description: Missing phrase or unable to interpret.
        "502":
          description: Internal interpreter error.

components:
  schemas:
    Offer:
      type: object
      properties:
        id:
          type: string
        price:
          type: string
        currency:
          type: string
        itineraries:
          type: array
          items:
            $ref: "#/components/schemas/Itinerary"
    Itinerary:
      type: object
      properties:
        duration:
          type: string
        segments:
          type: array
          items:
            $ref: "#/components/schemas/FlightSegment"
    FlightSegment:
      type: object
      properties:
        carrierCode:
          type: string
        number:
          type: string
        departure:
          type: string
        departureTime:
          type: string
        arrival:
          type: string
        arrivalTime:
          type: string
        aircraft:
          type: string
    AntiPhaserRequest:
      type: object
      required:
        - phrase
      properties:
        phrase:
          type: string
          description: Natural-language travel date phrase (e.g., "next Friday at 18:00").
        timezone:
          type: string
          description: IANA timezone (default UTC).
        referenceDate:
          type: string
          description: ISO date used as the anchor for relative phrases.
    AntiPhaserResponse:
      type: object
      properties:
        ok:
          type: boolean
        isoDate:
          type: string
          description: Parsed ISO date (YYYY-MM-DD).
        time:
          type: string
          description: Parsed time component (HH:MM) when present.
        confidence:
          type: number
          format: float
        explanation:
          type: string
        phrase:
          type: string
        timezone:
          type: string
    EscalatorUploadRequest:
      type: object
      required:
        - type
        - path
        - sender
      properties:
        type:
          type: string
          description: Classification of the payload (for example `transcript`, `log`, `alert`).
        path:
          type: string
          description: Folder prefix relative to the escalator root.
        sender:
          type: string
          description: Identifier of the caller (alias, session, or tool).
        fileName:
          type: string
          description: Optional explicit file name to use.
        fileEncoding:
          type: string
          description: Encoding for `file` (for example `utf8` or `base64`).
        contentType:
          type: string
          description: MIME type to apply to the stored object.
        file:
          type: string
          description: Raw payload (use when `fileEncoding` is `utf8`).
        fileBase64:
          type: string
          description: Base64 encoded payload (use for binary data).
        fileData:
          type: string
          description: Alias for `fileBase64`.
    EscalatorUploadResponse:
      type: object
      properties:
        ok:
          type: boolean
        key:
          type: string
          description: Fully qualified S3 key that received the payload.
        bytes:
          type: integer
        message:
          type: string
    DerDruckerMarkdownRequest:
      type: object
      description: Offer bundle produced by `recommend_destinations` or `search_flights`.
      additionalProperties: true
    DerDruckerMarkdownResponse:
      type: object
      properties:
        markdown:
          type: string
          description: Generated Markdown content.
        summary:
          type: string
        message:
          type: string
    DerDruckerTicketRequest:
      type: object
      description: Ticket generation payload (passenger, legs, template identifiers).
      additionalProperties: true
    DerDruckerTicketResponse:
      type: object
      properties:
        pdf:
          type: string
          description: Base64 encoded PDF ticket bundle.
        meta:
          type: object
        message:
          type: string
    ToolCatalogResponse:
      type: object
      properties:
        tools:
          type: array
          items:
            type: object
            properties:
              tool_name:
                type: string
              tool_description:
                type: string
              tool_route:
                type: string
        message:
          type: string
    DatetimeInterpretRequest:
      type: object
      required:
        - phrase
      properties:
        phrase:
          type: string
          description: Natural-language phrase to interpret.
        referenceDate:
          type: string
          description: ISO date used as reference for relative phrases.
        timeZone:
          type: string
          description: IANA timezone.
    DatetimeInterpretResponse:
      type: object
      properties:
        phrase:
          type: string
        isoDate:
          type: string
        confidence:
          type: number
          format: float
        explanation:
          type: string
        timeZone:
          type: string
