openapi: 3.0.3
info:
  title: dAIsy Tools - Amadeus and IATA
  version: 1.1.1
  description: HTTP tools for the Bedrock Agent to search flights via Amadeus and resolve IATA codes.
servers:
  - url: https://origin-daisy.onrender.com
paths:
  /tools/amadeus/search:
    description: Amadeus Flight Offers Search adapter exposed by the proxy server.
    post:
      operationId: amadeusSearch
      summary: Search flight offers
      description: Submit a request to Amadeus Flight Offers Search via the proxy and retrieve LH-only offers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - originLocationCode
                - destinationLocationCode
                - departureDate
                - adults
              properties:
                originLocationCode:
                  type: string
                  description: IATA origin code (for example, MUC)
                destinationLocationCode:
                  type: string
                  description: IATA destination code (for example, ZRH)
                departureDate:
                  type: string
                  format: date
                  description: Outbound date in ISO 8601 format (YYYY-MM-DD)
                returnDate:
                  type: string
                  format: date
                  nullable: true
                  description: Optional return date in ISO 8601 format (YYYY-MM-DD)
                adults:
                  type: integer
                  minimum: 1
                  default: 1
                  description: Number of adult passengers
                children:
                  type: integer
                  minimum: 0
                  description: Number of child passengers
                infants:
                  type: integer
                  minimum: 0
                  description: Number of infant passengers
                nonStop:
                  type: boolean
                  default: false
                  description: If true, return only non-stop options
                travelClass:
                  type: string
                  enum:
                    - ECONOMY
                    - PREMIUM_ECONOMY
                    - BUSINESS
                    - FIRST
                  description: Preferred cabin class
                currencyCode:
                  type: string
                  description: Currency code (ISO 4217), for example EUR
                includedAirlineCodes:
                  type: string
                  description: Only consider these airline codes (comma-separated)
                excludedAirlineCodes:
                  type: string
                  description: Exclude these airline codes (comma-separated)
                max:
                  type: integer
                  minimum: 1
                  maximum: 250
                  default: 10
                  description: Maximum number of offers to return
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  offers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Offer"
                  raw:
                    type: object
        "400":
          description: Bad Request
        "502":
          description: Upstream error

  /tools/iata/lookup:
    description: Deterministic IATA resolver backed by the proxy server.
    get:
      operationId: iataLookup
      summary: Resolve IATA code or city or airport name
      description: Look up IATA codes or names deterministically using the proxy database.
      parameters:
        - in: query
          name: term
          required: true
          schema:
            type: string
          description: IATA code (for example, MUC) or partial city or airport name (for example, Munich)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object

  /tools/amadeus/flex:
    description: One-call flexible dates selection and LH-only pricing (one-way).
    post:
      operationId: amadeusFlex
      summary: Flexible dates priced list
      description: Request the proxy to select cheapest days and return LH-only priced offers for one-way searches.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - originLocationCode
                - destinationLocationCode
              properties:
                originLocationCode:
                  type: string
                  description: IATA origin code (for example, MUC)
                destinationLocationCode:
                  type: string
                  description: IATA destination code (for example, ZRH)
                month:
                  type: string
                  description: Month window (YYYY-MM); alternative to departureDateFrom or departureDateTo
                departureDateFrom:
                  type: string
                  format: date
                  description: Start of date window (YYYY-MM-DD)
                departureDateTo:
                  type: string
                  format: date
                  description: End of date window (YYYY-MM-DD)
                oneWay:
                  type: boolean
                  default: true
                  description: Must be true to return priced results (calendar is internal)
                nonStop:
                  type: boolean
                  default: false
                  description: If true, return only non-stop options
                currencyCode:
                  type: string
                  description: Currency code (ISO 4217), for example EUR
                limit:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 5
                  description: Maximum number of cheapest days to select from calendar
                priceLimit:
                  type: integer
                  minimum: 1
                  maximum: 10
                  description: Maximum number of days to price (defaults to limit)
                adults:
                  type: integer
                  minimum: 1
                  default: 1
                  description: Number of adult passengers
                travelClass:
                  type: string
                  enum:
                    - ECONOMY
                    - PREMIUM_ECONOMY
                    - BUSINESS
                    - FIRST
                  description: Preferred cabin class
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: object
                  priced:
                    type: array
                    items:
                      type: object
                      properties:
                        departureDate:
                          type: string
                          format: date
                        offers:
                          type: array
                          items:
                            $ref: "#/components/schemas/Offer"
                required:
                  - priced
        "400":
          description: Bad Request
        "502":
          description: Upstream error

components:
  schemas:
    Offer:
      type: object
      properties:
        id:
          type: string
        price:
          type: string
        currency:
          type: string
        itineraries:
          type: array
          items:
            $ref: "#/components/schemas/Itinerary"
    Itinerary:
      type: object
      properties:
        duration:
          type: string
        segments:
          type: array
          items:
            $ref: "#/components/schemas/FlightSegment"
    FlightSegment:
      type: object
      properties:
        carrierCode:
          type: string
        number:
          type: string
        departure:
          type: string
        departureTime:
          type: string
        arrival:
          type: string
        arrivalTime:
          type: string
        aircraft:
          type: string
